# Generated by Django 2.1.7 on 2019-03-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('charity_number', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(blank=True, max_length=400, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=400, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.BigIntegerField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Charities',
                'ordering': ['name'],
            },
        ),
    ]
